fix comamnd error: 'NoneType' object has no attribute 'name'
idk why this suddenly broke as it worked before and i didnt touch this part of the code for months but i fixed i regardless and on top saved some CPU time when commands are ran in DMs.