fix exception in /csr2_wrlist
ERROR - Task exception was never retrieved
future: <Task finished name='discord-ui-view-timeout-e114e5dd974ce44d0b3c4b22a66ef6ab' coro=<PaginatedView.on_timeout() done, defined at /home/pi/jess/cogs/wrlist.py:222> exception=TypeError("PaginatedView.__init__() missing 1 required positional argument: 'csr2_version'")>
Traceback (most recent call last):
  File "/home/pi/jess/cogs/wrlist.py", line 224, in on_timeout
    new_view = PaginatedView(self.results, self.user, self.car, self.rarity, self.tier, self.csr2_version)
TypeError: PaginatedView.__init__() missing 1 required positional argument: 'csr2_version'